### PR TITLE
[TS] LPS-76664

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @natocesarrego,

Could you review this? It tries to align variable {userName} used in WF templates and profile picture shown in Notifications.

Thanks in advance

https://issues.liferay.com/browse/LPS-76664

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test

**Comment by natocesarrego** [comment]
Hi @dacousalr,

Have you sent this pull to me just for a double check from my side?

Just to let you know, you can send it straight to the PT. 😉 

Best.

**Comment by natocesarrego** [comment]
ci:retest

**Comment by dacousalr** [comment]
Exactly, @natocesarrego,

That was my intention. I will send it to the PT then.

Thank you very much

**Comment by natocesarrego** [comment]
Hi @dacousalr,

I can double check your pulls if you're unsure of your solution or would like a second opinion, ok? On a next pull, just let me know about it in the pull's description, once I'm reviewing just these cases for now due to my limited SME bandwidth. 😉

One more thing, Dani, can you please double check the CI results? I'm not one hundred percent sure if all failures are unrelated to this pull.

If you need anything else please let me know.

Thanks.

**Comment by dacousalr** [comment]
Hi @natocesarrego,

In this case I was unsure whether a better way to fix this would be possible or not before sending it to the PT. In any case, next time I will let you know in advance which kind of feedback is needed, as it should have been this time.

Regarding the CI results, I have reviewed the failing tests and all seem to be unrelated to this PR.

Sorry for any inconvenience caused and thanks!

**Pull request closed without merging**
